### ISSUE TITLE
Clean up Members page yaml

### ISSUE THREAD

**Issue by newtnoot** [hps-ucsd-2020/hps-ucsd-2020.github.io#70]
- Remove duplicate Ky
- Make an Admin team to put secretary + treasurer + outreach

**Comment by newtnoot** [comment]
- [ ] Add Andy
- [ ] Spell Check (research)
- [ ] Add Sharron to Finance

**Comment by EdwardNew** [comment]
- [ ] Add Jack to Drivetrain team
